services:
  # postgres database
  postgres:
    image: postgres:13.16
    container_name: $APP_NAME-postgres
    environment:
      POSTGRES_DB: $DATABASE_DB
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432 # database port

  # postgres admin interface
  postgres_admin:
    image: dpage/pgadmin4:2024-10-19-2
    container_name: $APP_NAME-postgres_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local']"
    ports:
      - 5433:80 # admin ui

